---
preset: extended
verbosity: INFO
resume: true
stateFile: build/.nyx-state.yml

commitMessageConventions:
  enabled:
    - gitmoji

git:
  remotes:
    origin:
      user: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      password: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"

releaseTypes:
  publicationServices:
    - github
  remoteRepositories:
    - origin

services:
  github:
    type: GITHUB
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_OWNER: lengors
      REPOSITORY_NAME: gradle-test-kt